### ISSUE TITLE
Non-Cached version for development not working

### ISSUE THREAD

**Issue by roberkules** [jessedhillon/pyramid_scss#3]
Setting the scss.cache to False doesn't work. After each change in the SCSS file restarting the paster is still needed.

**Comment by roberkules** [comment]
I don't see how you fixed this issue.

``` python
def __call__(self, scss, system):
    parser = Scss(scss_opts=self.options)

    if 'request' in system:
        request = system.get('request')
        request.response_content_type = 'text/css'
        key = request.matchdict.get('css_path')

        if not self.options.get('cache', False) or key not in self.cache:
            Logger.info('generating %s', key)
            self.cache[key] = parser.compile(scss)

        return self.cache.get(key)

    return parser.compile(scss)
```

Looking at this line:
`if not self.options.get('cache', False) or key not in self.cache:`

The output will always be cached, which requires restarting the paster for any change in the scss file to be recompiled (while developing).

**Comment by jessedhillon** [comment]
If you set the `cache` option to `False`, the first part of that clause will be true, causing the next lines to always be entered and `parser.compile` to be called. This means that every request will trigger a `parser.compile` call.

`not self.options.get('cache', False)` evaluates to `True`, causing the "then" portion of that construct to be executed.

Is it not working for you? I added some tests for, among other things, caching.

**Comment by roberkules** [comment]
Sorry about the if-statement. Of course it's correct.

But still, for some reason I don't get the updated version. If I debug it I can see that it's recompiled every time. Maybe the scss "template" content itself is cached somehow?

From my development.ini:

pyramid.reload_templates = true
pyramid.reload_assets = true
pyramid.debug_authorization = true
pyramid.debug_notfound = true
pyramid.debug_routematch = false
pyramid.debug_templates = true

scss.asset_path = myproject:static/css
scss.compress = False
scss.cache = False

running the paster as:

paster serve development.ini --reload

Only after I stop the paster and start it again, the css gets updated.
Any idea why it's not working for me?

**Comment by jessedhillon** [comment]
Did you get commit 5976fae6cc15c1c41675c1589cb83ad7d58ce2c4 which contains another part of the fix for this? Also, do you see the logging statement `Logger.info('generating %s', key)` generated each time?

Can you put the following statement `import pdb; pdb.set_trace()` above the line `return self.cache.get(key)` and inspect whether `self.cache` is updated?

If you are unfamiliar with `pdb`, you can get a quick reference here `http://docs.python.org/library/pdb.html#debugger-commands`. Quickly, what you would do here is:

``` python
---execution stopped---
pdb> !self
<ScssRenderer>
pdb> !self.cache
... contents of self.cache
```

**Comment by eevee** [comment]
This is still wrong, because `controller.py` does the following:

```
caching = request.registry.settings.get('scss.cache', False)
```

It's getting the literal string, `'false'`, which is a true value.  You used `as_bool` in the renderer factory, but not here.  So the renderer is indeed recompiling, but it's recompiling the old contents of the file.

In your defense, the ini format is a little bozotic.  :)

**Comment by eevee** [comment]
Also, `pyramid.settings` contains an `asbool` function already; you shouldn't need your own.

**Comment by jessedhillon** [comment]
Wow. I thought I had checked in changes that remove the attempted caching of file reads but I guess I had left that in there. Go ahead and pull the latest, I took that stuff out.

**Comment by jessedhillon** [comment]
@eevee Did you pull the latest? Does that work for you?

**Comment by eevee** [comment]
Hey, sorry; been a bit preoccupied.  Yes, master seems to work fine for me now.

**Comment by jessedhillon** [comment]
Folks, truly sorry that I've been absent from this project. I created this at a time when my work made it useful to do, and I got it working to the state I needed it in. I'll be making time in the near-future to integrate all these changes and requests. Bear with me!
